### ISSUE TITLE
brackets not needed in the software

### ISSUE THREAD

**Issue by Krishna41ram** [skarra/PRS#12]
1)	 Please see the degrees of the doctor. Removal of the brackets in the print program of the software will give a neat look. Please remove the defa
![capture1](https://user-images.githubusercontent.com/42244931/44133342-fbff1286-a07c-11e8-9419-ea5c9c83aca6.PNG)
ult brackets of the Program.

Thanks for receipt. No need to say "Receipt" but can be said as "**************towards registration of new visit or Revisit"
depending on the type of the visit.

**Comment by skarra** [comment]
Fixed it to look like this: 

![image](https://user-images.githubusercontent.com/633395/44154640-0ae5553e-a060-11e8-83eb-3e2eec9e6eb2.png)

**Comment by skarra** [comment]
Note: this is not yet pushed to any version.

**Comment by Krishna41ram** [comment]
Great Looks Good about degrees and receipt wording
