### ISSUE TITLE
Print receipt for registration charges made for old and new cases and indicate if waived

### ISSUE THREAD

**Issue by Krishna41ram** [skarra/PRS#14]
2)	If an option to print receipt/ acknowledgement is provided and printed as a line below the last line of the OPD registration data, it may not need another receipt to be issued which will save time and botheration to the registration clerk. It could say “ _Received Rupees XX towards new or old OPD Registration” For Poor Patients if charges waived it may read “The Registration Charges have been waived”_

**Comment by skarra** [comment]
I already fixed it via https://github.com/skarra/PRS/issues/5 Can you check?
