### ISSUE TITLE
modification to statistics

### ISSUE THREAD

**Issue by Krishna41ram** [skarra/PRS#15]
3)	In “View Statistics” button a provision of separating old and new patients may please be made. The Registration clerk has to deposit the daily collection to the accounts department with justification. A option button for old or new may be introduced before or after this.

**Comment by skarra** [comment]
I fixed it in this one: https://github.com/skarra/PRS/issues/3

Can you check?

**Comment by Krishna41ram** [comment]
just checked the statistics shows old and new separately. Thanks
Now  a button to make a registration free and statistics should also reflect the number of cases made free
