### ISSUE TITLE
Need improved messaging and options if no doctors from a dept are available for visits on a particular date

### ISSUE THREAD

**Issue by Krishna41ram** [skarra/PRS#17]
Dr B Krishna Ram besides Internal Medicine sees patients of Endocrinology and Metabolism, however Endocrinology & Metabolism is not shown as his availability while making registration of a patient as shown below
![capture3](https://user-images.githubusercontent.com/42244931/44335525-556a2400-a492-11e8-939d-e49532b32a95.PNG)
![capture4](https://user-images.githubusercontent.com/42244931/44335541-60bd4f80-a492-11e8-9f82-4729fa42998c.PNG)

**Comment by skarra** [comment]
20-08-2018 is a Sunday and your availability schedule as per the above screenshot says you are available only Mon / Wed / Fri that is why your name is not available when setting up new visits on 20-08-2018.

I can try to make it easier to understand.

**Comment by skarra** [comment]
After the fix here is how it looks if no doctor is available for a specified date.

![image](https://user-images.githubusercontent.com/633395/44626028-7683a800-a8ca-11e8-9857-966a51ec9657.png)

If another suitable date is selected here is how it looks:

![image](https://user-images.githubusercontent.com/633395/44626034-931fe000-a8ca-11e8-81f9-f6a8bf02cd1f.png)

**Comment by Krishna41ram** [comment]
20-08-2018 is a Sunday and your availability schedule as per the above screenshot says you are available only Mon / Wed / Fri that is why your name is not available when setting up new visits on 20-08-2018.

I can try to make it easier to understand.

Dear Sriram 20th August was Monday and Not Sunday. I checked from Calendar Today is 26th Sunday last Sunday was 19th

**Comment by Krishna41ram** [comment]
No Doctor available from the department message is ok
