### ISSUE TITLE
mismatch between fee charged and type of registration ie new or old

### ISSUE THREAD

**Issue by Krishna41ram** [skarra/PRS#21]
![reciept mismatch1](https://user-images.githubusercontent.com/42244931/50415421-e5551b80-0840-11e9-916d-6f98f2303036.png)
This registration is for a first visit to  a doctor and rightly charged Rs 30 but the receipt says " Old Case"
For a new case New registration may be mentioned.
Mr/Mrs ....... may also be omitted as their could be Kumari also and in any case the details of the patient is already printed on top of the form

**Comment by skarra** [comment]
I have fixed this now, and will be included in next release.
