### ISSUE TITLE
"New" / "Old" case should be computed for a doctor in the same department

### ISSUE THREAD

**Issue by Krishna41ram** [skarra/PRS#22]
![capture dept_fee mismatch1](https://user-images.githubusercontent.com/42244931/50415734-b2ac2280-0842-11e9-9eb8-a3155c4bddc9.png)

Dr Bisht sees cases in two departments 1) Internal Medicine and 2) Geriatrics. This patient was showing Dr Bisht in Internal Medicine but now registered in a Super Specialty ie Geriatrics, yet only charged 20, probably the software takes into consideration as doctor's second visit irrespective of the department

**Comment by skarra** [comment]
I have now fixed this and pushed v0.22 to Dropbox
