### ISSUE TITLE
problem not resolved fully

### ISSUE THREAD

**Issue by Krishna41ram** [skarra/PRS#24]
![capture_new](https://user-images.githubusercontent.com/42244931/53250405-564d6e00-36e0-11e9-8bec-04b8e4cd6219.PNG)
Though the charge of Rs 30 for a new visit to a new department. the display says

**Comment by Krishna41ram** [comment]
Though the charge of Rs 30 for a new visit to a new department. the display says "old". The charges are correct but department of Geriatrics is different from Internal medicine though Dr Bisth conducts both clinic

**Comment by skarra** [comment]
What version did you try out?.

**Comment by Krishna41ram** [comment]
v0.23

**Comment by skarra** [comment]
Pushed v0.24 with fix
