### ISSUE TITLE
Patient Stats

### ISSUE THREAD

**Issue by Krishna41ram** [skarra/PRS#26]
Please see the print of stats of 15/03/2019. For patients were seen. One new case and one old revisit case had been made free.
In the stats shown in (highlighted yellow) the output below, Please add the following as the clinic has to submit to the head office cashier.
New patients waived charges 1
Old patients waived charges  1
correct the figures accordingly highlighted with yellow pen, though one can guess from the total data. More explicit summary will ease the work of the clerks
![InkedCapture15032019f_LI](https://user-images.githubusercontent.com/42244931/54446380-cd6ca400-476c-11e9-9d48-75b07a29bc79.jpg)

**Comment by skarra** [comment]
If I put it in a summary table like this, will it work?

![image](https://user-images.githubusercontent.com/633395/54695399-1e6ef600-4ae7-11e9-8e2c-189259db5723.png)

**Comment by Krishna41ram** [comment]
It looks good. we may implement it
