### ISSUE TITLE
In View Statistics separate new and old patients

### ISSUE THREAD

**Issue by skarra** [skarra/PRS#3]
In View Statistics a provision of separating old and new patients may please be made. The Registration clerk has to deposit the daily collection to the accounts department with justification. An option button for old or new may be introduced before or after this.

**Comment by Krishna41ram** [comment]
unless a provision to make a patient free one cannot check statistics of free patients
![capture2](https://user-images.githubusercontent.com/42244931/44190334-def0bd80-a143-11e8-8dfa-5f9ede11acbb.PNG)
under new and old patients paid and free could be separated
