### ISSUE TITLE
Print receipt of amount received in the Print Visit view

### ISSUE THREAD

**Issue by skarra** [skarra/PRS#5]
If an option to print receipt/ acknowledgment is provided and printed as a line below the last line of the OPD registration data, it may not need another receipt to be issued which will save time and botheration to the registration clerk. It could say “ Received Rupees XX towards new or old OPD Registration” For Poor Patients, it read “The Registration Charges have been waived”

**Comment by skarra** [comment]
It will now look like this:

**Comment by Krishna41ram** [comment]
![capture5](https://user-images.githubusercontent.com/42244931/44786770-cad0a580-abb2-11e8-821e-99398f85b543.PNG)
Yes the software prints receipt. I request some changes in the format
1) Please remove the word receipt: and as such print as follows
a)" Received Rs 30 as a New Visit Charges" b) "Received Rs 20 as Revisit Charges" 3) "The Visit Charges have been waived"
