### ISSUE TITLE
Facilitate easy copying of department data from Sample DB into Prod DB

### ISSUE THREAD

**Issue by Krishna41ram** [skarra/PRS#8]

**Comment by skarra** [comment]
Original note: Apparently one db ie Sample db or PRS db is created for data of departments, doctors and patient. This does not permit copying departments or doctors data of Sample into PRS. If you fix this then it will be easy to copy the department and doctors data from sample to PRS.

**Comment by skarra** [comment]
This is going to be quite hard to do properly once we have the system running in production. There are lots of tricky corner cases and decisions to make: what do we do with existing departments, what about existing visits and doctors, and a department is removed, etc. 

Given that department list does not change very often, I do not plan to fix this.

**Comment by Krishna41ram** [comment]
Thanks we will redo the doctors and departments in PRS db also
